### ISSUE TITLE
Is this great tool currently executable?

### ISSUE THREAD

**Issue by 4tler** [thomergil/gopro-map-sync#1]
This tool is exactly what I need. Especially as it allows custom TMS services as a map. 

Unfortunately it doesn't seem to work anymore. I tried to run it on Windows 10 with Docker but I always get the following error message. 

`2024-05-30 19:05:47,080 -- Reading GPX file /videos/GX010054.gpx
2024-05-30 19:05:47,084 -- Cleaning GPX file /videos/GX010054.gpx
2024-05-30 19:05:47,088 -- Duration /videos/GX010054.gpx : 0:00:10.260000
2024-05-30 19:05:47,088 -- Concatenating all GPX files
Traceback (most recent call last):
  File "/src/gopro-map-sync/gpxmapmovie", line 351, in <module>
    main()
  File "/src/gopro-map-sync/gpxmapmovie", line 321, in main
    if arg.startswith('--') and pass_args[0] and not pass_args[0].startswith('--'):
IndexError: list index out of range`

Camera is GoPro 9 Black with latest firmware.
Is there still a chance to get the tool running?

**Comment by thomergil** [comment]
Investigating.

**Comment by thomergil** [comment]
For my own purposes, reformatting @4tler bug report:

```
2024-05-30 19:05:47,080 -- Reading GPX file /videos/GX010054.gpx
2024-05-30 19:05:47,084 -- Cleaning GPX file /videos/GX010054.gpx
2024-05-30 19:05:47,088 -- Duration /videos/GX010054.gpx : 0:00:10.260000
2024-05-30 19:05:47,088 -- Concatenating all GPX files Traceback (most recent call last): File "/src/gopro-map-sync/gpxmapmovie", line 351, in <module> main() File "/src/gopro-map-sync/gpxmapmovie", line 321, in main if arg.startswith('--') and pass_args[0] and not pass_args[0].startswith('--'): IndexError: list index out of range
```

**Comment by thomergil** [comment]
@4tler, can you show me the exact and full command line that you ran to get this error?

**Comment by 4tler** [comment]
Thats the docker command:

```docker run --mount="type=bind,source=C:/Users/David/Downloads/videos,target=/videos/" thomergil/gpxmapmovie info --input=/videos/GX010053.MP4 --output=/videos/GX010053.mp4```

And thats the result:
```2024-05-30 21:30:23,634 -- Reading GPX file /videos/GX010053.gpx
2024-05-30 21:30:23,701 -- Cleaning GPX file /videos/GX010053.gpx
2024-05-30 21:30:23,999 -- Duration /videos/GX010053.gpx : 0:13:11.810000
2024-05-30 21:30:23,999 -- Concatenating all GPX files
Traceback (most recent call last):
  File "/src/gopro-map-sync/gpxmapmovie", line 351, in <module>
    main()
  File "/src/gopro-map-sync/gpxmapmovie", line 321, in main
    if arg.startswith('--') and pass_args[0] and not pass_args[0].startswith('--'):
IndexError: list index out of range```

**Comment by thomergil** [comment]
The first thing I'm wondering is why you're getting that error on line 321 when this line of code is actually near line 360. Are you running the latest version of the code, @4tler?

**Comment by thomergil** [comment]
Also, looking at your command line, there seems to be an `info` that shouldn't be there? @4tler?

**Comment by 4tler** [comment]
I use the docker image under windows with the help of docker dektop. The image is as described here in Git: thomergil/gpxmapmovie:latest

**Comment by thomergil** [comment]
Perhaps you meant `--debug info` and you removed the `--debug` but not the `info`?

**Comment by 4tler** [comment]
ok, i got this with the right command:

```docker run --mount="type=bind,source=C:/Users/David/Downloads/videos,target=/videos/" thomergil/gpxmapmovie  --input=/videos/GX010053.MP4 --output=/videos/GX010053_map.mp4 --debug info```
```2024-05-30 21:46:15,193 -- Reading GPX file /videos/GX010053.gpx
2024-05-30 21:46:15,256 -- Cleaning GPX file /videos/GX010053.gpx
2024-05-30 21:46:15,543 -- Duration /videos/GX010053.gpx : 0:13:11.810000
2024-05-30 21:46:15,543 -- Concatenating all GPX files
2024-05-30 21:46:15,606 -- java -jar /src/gpx-animator-1.6/build/libs/gpx-animator-1.6.0-all.jar --output=/videos/GX010053_map.mp4 --debug info --input /tmp/tmpdqfwbtfz --total-time 791770
21:46:16.055 [main] ERROR app.gpx_animator.Main - unrecognised option '--output=/videos/GX010053_map.mp4'
run program with --help option to print help```

**Comment by thomergil** [comment]
Documentation tells you to leave out the `=` :)

**Comment by 4tler** [comment]
thats true ... here the right command if someone will need it someday: 

```docker run --mount="type=bind,source=C:/Users/David/Downloads/videos,target=/videos/" thomergil/gpxmapmovie  --input /videos/GX010053.MP4 --output /videos/GX010053_map.MP4```

Thank you very much for the support.

**Comment by thomergil** [comment]
Excellent. I will improve the output of the command to make it more clear what the problem is.

**Comment by 4tler** [comment]
I will be working intensively with the tool over the next few days. If I have any additions for the readme, I can add them if that's ok. Maybe there will also be a small Windows HowTo.
